// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *dropdown → dropdown*
 */
export interface GropdownDocumentDataDropdownItem {
  /**
   * link field in *dropdown → dropdown*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gropdown.dropdown[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for dropdown documents
 */
interface GropdownDocumentData {
  /**
   * dropdown field in *dropdown*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gropdown.dropdown[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  dropdown: prismic.GroupField<Simplify<GropdownDocumentDataDropdownItem>>;
}

/**
 * dropdown document from Prismic
 *
 * - **API ID**: `gropdown`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GropdownDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GropdownDocumentData>,
    "gropdown",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | LocationSlice
  | CooperateLinkSlice
  | PartnersSlice
  | VacenciesSlice
  | TeamSlice
  | ServicesSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *settings → Footer_link*
 */
export interface SettingsDocumentDataFooterLinkItem {
  /**
   * link field in *settings → Footer_link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_link[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * lable field in *settings → Footer_link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_link[].lable
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lable: prismic.KeyTextField;
}

/**
 * Item in *settings → Footer Icon*
 */
export interface SettingsDocumentDataFooterIconItem {
  /**
   * link field in *settings → Footer Icon*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon field in *settings → Footer Icon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[].icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = TopNavbarSlice;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * SIte Title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * site description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_description: prismic.KeyTextField;

  /**
   * OG Image field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Footer logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer_link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_link: prismic.GroupField<Simplify<SettingsDocumentDataFooterLinkItem>>;

  /**
   * Footer Icon field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_icon[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_icon: prismic.GroupField<Simplify<SettingsDocumentDataFooterIconItem>>;

  /**
   * Slice Zone field in *settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | GropdownDocument
  | HomepageDocument
  | SettingsDocument;

/**
 * Item in *CooperateLink → Default → Primary → Cooperate links*
 */
export interface CooperateLinkSliceDefaultPrimaryCooperateLinksItem {
  /**
   * title field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * link field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon field in *CooperateLink → Default → Primary → Cooperate links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;
}

/**
 * Primary content in *CooperateLink → Default → Primary*
 */
export interface CooperateLinkSliceDefaultPrimary {
  /**
   * Heading field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Contact field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;

  /**
   * Cooperate links field in *CooperateLink → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cooperate_link.default.primary.cooperate_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cooperate_links: prismic.GroupField<
    Simplify<CooperateLinkSliceDefaultPrimaryCooperateLinksItem>
  >;
}

/**
 * Default variation for CooperateLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CooperateLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CooperateLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CooperateLink*
 */
type CooperateLinkSliceVariation = CooperateLinkSliceDefault;

/**
 * CooperateLink Shared Slice
 *
 * - **API ID**: `cooperate_link`
 * - **Description**: CooperateLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CooperateLinkSlice = prismic.SharedSlice<
  "cooperate_link",
  CooperateLinkSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Hexa Grid*
 */
export interface HeroSliceDefaultPrimaryHexaGridItem {
  /**
   * Hexa Image field in *Hero → Default → Primary → Hexa Grid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hexa_grid[].hexa_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hexa_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * contant field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.contant
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contant: prismic.RichTextField;

  /**
   * Backgroung Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroung_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroung_image: prismic.ImageField<never>;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Sub Headeing field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Hexa Grid field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hexa_grid[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hexa_grid: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryHexaGridItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Location → Default → Primary → location card*
 */
export interface LocationSliceDefaultPrimaryLocationCardItem {
  /**
   * Title field in *Location → Default → Primary → location card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Place field in *Location → Default → Primary → location card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[].place
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place: prismic.KeyTextField;
}

/**
 * Primary content in *Location → Default → Primary*
 */
export interface LocationSliceDefaultPrimary {
  /**
   * Heading field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Contact field in *Location → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;

  /**
   * location card field in *Location → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  location_card: prismic.GroupField<
    Simplify<LocationSliceDefaultPrimaryLocationCardItem>
  >;

  /**
   * location map field in *Location → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.location_map
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location_map: prismic.GeoPointField;
}

/**
 * Default variation for Location Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Location*
 */
type LocationSliceVariation = LocationSliceDefault;

/**
 * Location Shared Slice
 *
 * - **API ID**: `location`
 * - **Description**: Location
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSlice = prismic.SharedSlice<
  "location",
  LocationSliceVariation
>;

/**
 * Item in *Partners → Default → Primary → Partners card*
 */
export interface PartnersSliceDefaultPrimaryPartnersCardItem {
  /**
   * card image field in *Partners → Default → Primary → Partners card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card link field in *Partners → Default → Primary → Partners card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Heading field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * Partners card field in *Partners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.partners_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partners_card: prismic.GroupField<
    Simplify<PartnersSliceDefaultPrimaryPartnersCardItem>
  >;

  /**
   * Contact field in *Partners → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Item in *Services → Default → Primary → card*
 */
export interface ServicesSliceDefaultPrimaryCardItem {
  /**
   * card image field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card link field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * card heading field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_heading: prismic.RichTextField;

  /**
   * card sub heading field in *Services → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[].card_sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_sub_heading: prismic.RichTextField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * lable field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.lable
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lable: prismic.RichTextField;

  /**
   * description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * card field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryCardItem>>;

  /**
   * span lable field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.span_lable
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  span_lable: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Team → Default → Primary → team card*
 */
export interface TeamSliceDefaultPrimaryTeamCardItem {
  /**
   * person image field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].person_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  person_image: prismic.ImageField<never>;

  /**
   * Name field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * desigation field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].desigation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  desigation: prismic.RichTextField;

  /**
   * feild field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].feild
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feild: prismic.RichTextField;

  /**
   * description field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * card link field in *Team → Default → Primary → team card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * contact field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;

  /**
   * team card field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_card: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryTeamCardItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Header → Default → Primary → Navbar*
 */
export interface TopNavbarSliceDefaultPrimaryNavbarItem {
  /**
   * Link field in *Header → Default → Primary → Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.navbar[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * lable field in *Header → Default → Primary → Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.navbar[].lable
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lable: prismic.KeyTextField;
}

/**
 * Item in *Header → Default → Primary → service sub menu*
 */
export interface TopNavbarSliceDefaultPrimaryServiceSubMenuItem {
  /**
   * link field in *Header → Default → Primary → service sub menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.service_sub_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * lable field in *Header → Default → Primary → service sub menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.service_sub_menu[].lable
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lable: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface TopNavbarSliceDefaultPrimary {
  /**
   * Logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navbar field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.navbar[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navbar: prismic.GroupField<Simplify<TopNavbarSliceDefaultPrimaryNavbarItem>>;

  /**
   * service sub menu field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.default.primary.service_sub_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service_sub_menu: prismic.GroupField<
    Simplify<TopNavbarSliceDefaultPrimaryServiceSubMenuItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopNavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopNavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type TopNavbarSliceVariation = TopNavbarSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `top_navbar`
 * - **Description**: TopNavbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopNavbarSlice = prismic.SharedSlice<
  "top_navbar",
  TopNavbarSliceVariation
>;

/**
 * Item in *Vacencies → Default → Primary → vacency card*
 */
export interface VacenciesSliceDefaultPrimaryVacencyCardItem {
  /**
   * card image field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * card heading field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_heading: prismic.RichTextField;

  /**
   * card Button field in *Vacencies → Default → Primary → vacency card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[].card_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Vacencies → Default → Primary*
 */
export interface VacenciesSliceDefaultPrimary {
  /**
   * Heading field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Headeing field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.sub_headeing
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headeing: prismic.RichTextField;

  /**
   * vacency card field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.vacency_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  vacency_card: prismic.GroupField<
    Simplify<VacenciesSliceDefaultPrimaryVacencyCardItem>
  >;

  /**
   * Conatct field in *Vacencies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacencies.default.primary.conatct
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conatct: prismic.RichTextField;
}

/**
 * Default variation for Vacencies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VacenciesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VacenciesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vacencies*
 */
type VacenciesSliceVariation = VacenciesSliceDefault;

/**
 * Vacencies Shared Slice
 *
 * - **API ID**: `vacencies`
 * - **Description**: Vacencies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VacenciesSlice = prismic.SharedSlice<
  "vacencies",
  VacenciesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GropdownDocument,
      GropdownDocumentData,
      GropdownDocumentDataDropdownItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataFooterLinkItem,
      SettingsDocumentDataFooterIconItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      CooperateLinkSlice,
      CooperateLinkSliceDefaultPrimaryCooperateLinksItem,
      CooperateLinkSliceDefaultPrimary,
      CooperateLinkSliceVariation,
      CooperateLinkSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryHexaGridItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LocationSlice,
      LocationSliceDefaultPrimaryLocationCardItem,
      LocationSliceDefaultPrimary,
      LocationSliceVariation,
      LocationSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryPartnersCardItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryCardItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryTeamCardItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TopNavbarSlice,
      TopNavbarSliceDefaultPrimaryNavbarItem,
      TopNavbarSliceDefaultPrimaryServiceSubMenuItem,
      TopNavbarSliceDefaultPrimary,
      TopNavbarSliceVariation,
      TopNavbarSliceDefault,
      VacenciesSlice,
      VacenciesSliceDefaultPrimaryVacencyCardItem,
      VacenciesSliceDefaultPrimary,
      VacenciesSliceVariation,
      VacenciesSliceDefault,
    };
  }
}
