// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cooperate_link: dynamic(() => import("./CooperateLink")),
  hero: dynamic(() => import("./Hero")),
  location: dynamic(() => import("./Location")),
  partners: dynamic(() => import("./Partners")),
  services: dynamic(() => import("./Services")),
  team: dynamic(() => import("./Team")),
  vacencies: dynamic(() => import("./Vacencies")),
};
